version: '2'

services:

  master:
    build: ./redis
    image: master
    container_name: master
    hostname: master
    environment:
      NODE_TYPE: master
  slave1:
    build: ./redis
    image: slave1
    container_name: slave1
    hostname: slave1
    environment:
      NODE_TYPE: slave
    links:
      - master
  slave2:
    build: ./redis
    image: slave2
    container_name: slave2
    hostname: slave2
    environment:
      NODE_TYPE: slave
    links:
      - master
      - slave1

  sentinel1:
    build: ./redis
    image: sentinel1
    container_name: sentinel1
    hostname: sentinel1
    environment:
      NODE_TYPE: sentinel
    links:
      - master
      - slave1
      - slave2
  sentinel2:
    build: ./redis
    image: sentinel2
    container_name: sentinel2
    hostname: sentinel2
    environment:
      NODE_TYPE: sentinel
    links:
      - master
      - slave1
      - slave2
      - sentinel1
  sentinel3:
    build: ./redis
    image: sentinel3
    container_name: sentinel3
    hostname: sentinel3
    environment:
      NODE_TYPE: sentinel
    links:
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2

  php:
    build: ./php
    image: php
    container_name: php
    hostname: php
    volumes:
      - ./php/assets/var/www:/var/www
    links:
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2
      - sentinel3
    ports:
      - 8080:80
