Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "controller" do |controller|
    controller.vm.network :private_network, ip: "172.17.177.11"
  end
  config.vm.define "db" do |db|
    db.vm.network :private_network, ip: "172.17.177.21"
  end
  config.vm.define "api" do |api|
    api.vm.network :private_network, ip: "172.17.177.22"
  end
  config.vm.define "www" do |www|
    www.vm.network :private_network, ip: "172.17.177.23"
  end
end
